/** Negative prompts (NP001–NP100) — prevent unwanted generation */
export const NEGATIVE_PROMPTS: string[] = [
  "redesigned product",
  "distorted product geometry",
  "warped product proportions",
  "incorrect frame shape",
  "missing product components",
  "altered product materials",
  "different product",
  "replaced product",
  "stylized product",
  "cartoon style",
  "illustration style",
  "anime style",
  "distorted logo",
  "logo covering product",
  "blurred product",
  "motion blur",
  "low resolution",
  "poor lighting",
  "harsh shadows hiding product",
  "cluttered background",
  "distracting objects",
  "background overpowering product",
  "floating product",
  "product cut off",
  "poorly centered composition",
  "fisheye effect",
  "human models",
  "human hands touching product",
  "human faces",
  "AI artifacts",
  "visual glitches",
  "pixelation",
  "fantasy style",
  "incorrect reflections",
  "unrealistic color palette",
  "text overlay",
  "watermark",
  "turning eyeglasses into sunglasses",
  "changing product type",
  "duplicate or extra products in frame",
  "mismatched shadow direction",
  "plastic 3D render look",
  "overexposed blown highlights",
  "visible compositing seams or cut-out edges",
  "sticker pasted-on appearance",
  "logos or branded objects added to the scene",
];

export function getNegativePromptsText(): string {
  return NEGATIVE_PROMPTS.join(", ");
}
